/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AttributeRow: typeof import('./src/components/AttributeRow.vue')['default']
    AttributeRowAdd: typeof import('./src/components/AttributeRowAdd.vue')['default']
    BaseRow: typeof import('./src/components/BaseRow.vue')['default']
    BuiltInAttrs: typeof import('./src/components/BuiltInAttrs.vue')['default']
    DbAttrs: typeof import('./src/components/DbAttrs.vue')['default']
    DbRow: typeof import('./src/components/DbRow.vue')['default']
    DebugInfo: typeof import('./src/components/DebugInfo.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
    TDateRangePicker: typeof import('tdesign-vue-next')['DateRangePicker']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TOption: typeof import('tdesign-vue-next')['Option']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
  }
}
